// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  hoverableTable: string;
  search: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
